BEGIN_SYMBOL_DEFINITIONS

	<!-- CATENTRY table -->
	COLS:CATENTRY_ESSENTIALS=CATENTRY:CATENTRY_ID,CATENTTYPE_ID
	
END_SYMBOL_DEFINITIONS

BEGIN_XPATH_TO_SQL_STATEMENT
	name=/CatalogEntry[CatalogEntryIdentifier[(UniqueID=)]]+MyCompany_CatalogEntryEssentials
	base_table=CATENTRY
	sql=
		SELECT 
				CATENTRY.$COLS:CATENTRY_ESSENTIALS$
		FROM
				CATENTRY
		WHERE
               CATENTRY.CATENTRY_ID = (?UniqueID?)
END_XPATH_TO_SQL_STATEMENT

